from django.urls import path

from .utils.utils import DownloadTemplateView, SaveImportedQuestionsView, ImportQuestionsView, ExportQuestionsView
from .view.category import (
    CategoriesView,
    AddCategoryView,
    EditCategoryView,
    GetCategoryTestsView,
    GetTestQuestionsCountView,
)
from .view.generation import GenerationDownloadView, GenerationRunView, GenerationView
from .view.hemis_users import (
    ImportStudentsFromHemisStreamView,
    ImportStaffFromHemisStreamView,
    ImportStudentsByGroupStreamView,
    GroupListView,
)
from .view.site import site_settings_view
from .view.test import (
    QuestionView,
    AddQuestionView,
    DeleteTestView,
    EditTestView,
    AddQuestionTestView,
    QuestionDetailApiView,
    QuestionUpdateApiView,
    QuestionDeleteApiView,
    AssignTestView,
    ToggleActiveView,
    AddAssignTestView,
    DeleteAssignmentView,
    EditAssignTestView,
    ViewAssignTestView,
    ExportAssignTestView,
)
from .views import (
    MainView,
    ProfileView,
    UsersView,
    ResultsView,
    DeleteStudentResultView,
    AddUserView,
    EditUserView,
    ViewTestDetailsView,
    assign_students_to_test,
    ToggleAuthView,
    GrantAllAuthView,
    RevokeAllAuthView,
    ImportUsersExcelView,
)
from .view.roles import RolesView

urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('settings/site/', site_settings_view, name='site_settings'),
    path('users/', UsersView.as_view(), name='users'),
    path('users/<int:id>/toggle-auth/', ToggleAuthView.as_view(), name='toggle-auth'),
    path('users/grant-all-auth/', GrantAllAuthView.as_view(), name='grant-all-auth'),
    path('users/revoke-all-auth/', RevokeAllAuthView.as_view(), name='revoke-all-auth'),
    path('users/add/', AddUserView.as_view(), name='add-user'),
    path('users/<int:id>/edit/', EditUserView.as_view(), name='edit-user'),
    path('users/<int:id>/delete/', UsersView.as_view(), name='delete-user'),
    path('users/import-excel/', ImportUsersExcelView.as_view(), name='import-users-excel'),
    path('categories/', CategoriesView.as_view(), name='categories'),
    path('categories/add/', AddCategoryView.as_view(), name='add-category'),
    path('categories/<int:category_id>/edit/', EditCategoryView.as_view(), name='edit-category'),
    path('categories/<int:category_id>/delete/', CategoriesView.as_view(), name='delete-category'),
    path('categories/tests/', GetCategoryTestsView.as_view(), name='category-tests'),
    path('tests/question-count/', GetTestQuestionsCountView.as_view(), name='test-questions-count'),
    path('tests/', QuestionView.as_view(), name='question'),
    path('tests/', QuestionView.as_view(), name='questions'),
    path('tests/add/', AddQuestionView.as_view(), name='add-question'),
    path('tests/<int:test_id>/edit/', EditTestView.as_view(), name='edit-test'),
    path('tests/<int:test_id>/delete/', DeleteTestView.as_view(), name='delete-test'),
    path('tests/<int:test_id>/details/', ViewTestDetailsView.as_view(), name='view-test-details'),
    path('tests/<int:test_id>/questions/add/', AddQuestionTestView.as_view(), name='add-question-test'),
    path('tests/<int:test_id>/questions/<int:question_id>/detail/', QuestionDetailApiView.as_view(), name='question-detail'),
    path('tests/<int:test_id>/questions/<int:question_id>/update/', QuestionUpdateApiView.as_view(), name='question-update'),
    path('tests/<int:test_id>/questions/<int:question_id>/delete/', QuestionDeleteApiView.as_view(), name='question-delete'),
    path('tests/<int:test_id>/questions/import/', ImportQuestionsView.as_view(), name='import-questions'),
    path('tests/import/save/', SaveImportedQuestionsView.as_view(), name='save-imported-questions'),
    path('tests/template/download/', DownloadTemplateView.as_view(), name='download-template'),
    path('tests/<int:test_id>/export/<str:format_type>/', ExportQuestionsView.as_view(), name='export-questions'),
    path('tests/<int:test_id>/students/', assign_students_to_test, name='assign-students-to-test'),
    path('generation/', GenerationView.as_view(), name='generation'),
    path('generation/run/', GenerationRunView.as_view(), name='generation-run'),
    path('generation/download/<str:run_id>/<path:filename>/', GenerationDownloadView.as_view(), name='generation-download'),
    path('assignments/', AssignTestView.as_view(), name='assign-test'),
    path('assignments/add/', AddAssignTestView.as_view(), name='add-assign-test'),
    path('assignments/<int:assignment_id>/edit/', EditAssignTestView.as_view(), name='edit-assign-test'),
    path('assignments/<int:assignment_id>/view/', ViewAssignTestView.as_view(), name='view-assign-test'),
    path('assignments/<int:assignment_id>/export/', ExportAssignTestView.as_view(), name='export-assign-test'),
    path('assignments/<int:assignment_id>/delete/', DeleteAssignmentView.as_view(), name='delete-assignment'),
    path('assignments/<int:assignment_id>/toggle-active/', ToggleActiveView.as_view(), name='toggle-active'),
    path('imports/students/', ImportStudentsFromHemisStreamView.as_view(), name='import_students'),
    path('imports/staff/', ImportStaffFromHemisStreamView.as_view(), name='import_staff'),
    path('imports/students/by-group/', ImportStudentsByGroupStreamView.as_view(), name='import-students-by-group'),
    path('groups/', GroupListView.as_view(), name='group-list'),
    path('results/', ResultsView.as_view(), name='results'),
    path('results/<int:test_id>/delete/', DeleteStudentResultView.as_view(), name='delete-student-result'),
    path('roles/', RolesView.as_view(), name='roles'),
]
